# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc628e08ad28a14992bd98557536a8eee33244629db8d171010aa16e7ead9992f1d14425ef1d2e0249e6748ad11e6e0bf56a0646b891e7110560af887df4c9bb

test:
  secret_key_base: 8e45ef6cefbc2c21c3a25924bb688522e0784d47338c885b25d640c9e15f2671d7737bc2429bee47bef55347a193a79e9c696b52abb5eef0591d65ed50af5155

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
